---
title: "Problem Set 2"
author: "Neeharika , Francesca, Giacomo, Kun and Noor"
date: "01/02/2022"
output: pdf_document
---

```{r}
install.packages("readxl")
library(readxl)
data<- read_excel("~/Desktop/PHD/Econometrics/Sem 2/Problem Set 2/problem_set_2.xls")
View(data)
summary(data)
names(data)
install.packages("stargazer")
library(stargazer)
data$age_sq<-data$age^2
data$age_cube<-data$age^3
data$age_4<-data$age^4
data$yob_sq<-data$yob^2
data$yob_cube<-data$yob^3
data$yob_4<-data$yob^4
reg1 <- lm(logearn~schooling+age+age_sq+age_cube+age_4+yob+yob_sq+yob_cube+yob_4, data = data)
summary(reg1)
stargazer(reg1)
abline(reg1, col = "blue")
plot(reg1)

```


```{r}
data$LAW <- ifelse (data$yob >= 33, 1, 0)
reg6<- lm(schooling ~ LAW, data = data)
stargazer(reg6)
reg7<- lm(logearn ~ LAW, data = data )
stargazer(reg7)
0.161749 /0.99034
#0.1633267
library(tidyverse)
install.packages("ivreg")
library(ivreg)
a<-ivreg(logearn~schooling|LAW, data = data)
stargazer(a)
```
```{r}
data$leave<-ifelse(data$schooling < 15,1,0) #if someone left school before 15 = 1 and 0 otherwise
View(data)
table
leave_tab<-table(data$leave)
leave_tab
prop.table(leave_tab)#proportion table
data$prob<-with(data, ave(leave,yob))
#install.packages("tidyverse")
#install.packages("ggplot2")
#ggplot(data = data, aes(data$schooling, data$yob), geo)
plot1<-plot(data$yob, data$prob, vline(col="blue"))
install.packages("ggplot2")
library(ggplot2)
ggplot(data = data, 
       mapping = aes(x = yob, 
                     y = prob))+
  geom_point(size = 1) + labs(title = "Probability of a person leaving school before 15 against the year of birth")

```
```{r}
ggplot(data = data, mapping = aes(x = yob, 
                                  y = schooling))+
  geom_point(size = 1) + labs(title = "Binscatter : Schooling and Year of Birth")
```
```{r}
ggplot(data = data, 
       mapping = aes(x = yob,
                     y = logearn)) +
  geom_point(size = 2, colour = "dark blue") +labs(title = "Binscatter : Schooling and Year of Birth",
                                                  xlab = "Year of Birth",
                                                  ylab = "Log Earnings")

```

